// <auto-generated />
using System;
using Catalyte.Aquitas.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Catalyte.Aquitas.Data.Migrations
{
    [DbContext(typeof(ApparelCtx))]
    [Migration("20211004153925_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.LineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductID");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer")
                        .HasColumnName("PurchaseID");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("LineItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2021, 10, 4, 15, 39, 24, 705, DateTimeKind.Utc).AddTicks(9727),
                            DateModified = new DateTime(2021, 10, 4, 15, 39, 24, 705, DateTimeKind.Utc).AddTicks(9734),
                            ProductId = 1,
                            PurchaseId = 1,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Demographic")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GlobalProductCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryColorCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecondaryColorCode")
                        .HasColumnType("text");

                    b.Property<string>("StyleNumber")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            Category = "Hockey",
                            DateCreated = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(1676),
                            DateModified = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(2312),
                            Demographic = "Women",
                            GlobalProductCode = "po-ZQAHBOE",
                            ReleaseDate = new DateTime(2021, 10, 4, 11, 39, 24, 700, DateTimeKind.Local).AddTicks(8469),
                            StyleNumber = "scISBXS",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            Category = "Skateboarding",
                            DateCreated = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3157),
                            DateModified = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3159),
                            Demographic = "Men",
                            GlobalProductCode = "po-LOVWKBW",
                            ReleaseDate = new DateTime(2021, 10, 4, 11, 39, 24, 704, DateTimeKind.Local).AddTicks(3110),
                            StyleNumber = "scWZLQD",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            Category = "Baseball",
                            DateCreated = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3178),
                            DateModified = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3179),
                            Demographic = "Women",
                            GlobalProductCode = "po-WXRJZPA",
                            ReleaseDate = new DateTime(2021, 10, 4, 11, 39, 24, 704, DateTimeKind.Local).AddTicks(3171),
                            StyleNumber = "scCPCJF",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            Category = "Football",
                            DateCreated = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3194),
                            DateModified = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3196),
                            Demographic = "Men",
                            GlobalProductCode = "po-LRPIFHZ",
                            ReleaseDate = new DateTime(2021, 10, 4, 11, 39, 24, 704, DateTimeKind.Local).AddTicks(3190),
                            StyleNumber = "scRGMRH",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            Category = "Boxing",
                            DateCreated = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3209),
                            DateModified = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3211),
                            Demographic = "Men",
                            GlobalProductCode = "po-RPRXWNL",
                            ReleaseDate = new DateTime(2021, 10, 4, 11, 39, 24, 704, DateTimeKind.Local).AddTicks(3204),
                            StyleNumber = "scVKOTH",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            Category = "Soccer",
                            DateCreated = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3232),
                            DateModified = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3234),
                            Demographic = "Men",
                            GlobalProductCode = "po-YSNFPKK",
                            ReleaseDate = new DateTime(2021, 10, 4, 11, 39, 24, 704, DateTimeKind.Local).AddTicks(3227),
                            StyleNumber = "scHWIYL",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 7,
                            Active = false,
                            Category = "Baseball",
                            DateCreated = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3248),
                            DateModified = new DateTime(2021, 10, 4, 15, 39, 24, 704, DateTimeKind.Utc).AddTicks(3250),
                            Demographic = "Men",
                            GlobalProductCode = "po-QERRRXL",
                            ReleaseDate = new DateTime(2021, 10, 4, 11, 39, 24, 704, DateTimeKind.Local).AddTicks(3243),
                            StyleNumber = "scALLJY",
                            Type = "Pant"
                        });
                });

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BillingCity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingPhone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("BillingState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("BillingStreet")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingStreet2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingZip")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeliveryCity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeliveryFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeliveryLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeliveryState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("DeliveryStreet")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeliveryStreet2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DeliveryZip")
                        .HasMaxLength(10)
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingCity = "Atlanta",
                            BillingEmail = "customer@home.com",
                            BillingPhone = "(714) 345-8765",
                            BillingState = "GA",
                            BillingStreet = "123 Main",
                            BillingStreet2 = "Apt A",
                            BillingZip = "31675",
                            DateCreated = new DateTime(2021, 10, 4, 15, 39, 24, 706, DateTimeKind.Utc).AddTicks(8369),
                            DateModified = new DateTime(2021, 10, 4, 15, 39, 24, 706, DateTimeKind.Utc).AddTicks(8383),
                            DeliveryCity = "Birmingham",
                            DeliveryFirstName = "Max",
                            DeliveryLastName = "Space",
                            DeliveryState = "AL",
                            DeliveryStreet = "123 Hickley",
                            DeliveryZip = 43690,
                            OrderDate = new DateTime(2021, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.LineItem", b =>
                {
                    b.HasOne("Catalyte.Aquitas.Data.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalyte.Aquitas.Data.Model.Purchase", "Purchase")
                        .WithMany("LineItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.Purchase", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
