// <auto-generated />
using System;
using Catalyte.Aquitas.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Catalyte.Aquitas.Data.Migrations
{
    [DbContext(typeof(ApparelCtx))]
    partial class ApparelCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.AquitasUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AquitasUsers");
                });

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EmployeeSize")
                        .HasColumnType("integer");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrivateCompany")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reviews")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.LineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductID");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer")
                        .HasColumnName("PurchaseID");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("LineItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2021, 10, 30, 20, 36, 57, 111, DateTimeKind.Utc).AddTicks(6625),
                            DateModified = new DateTime(2021, 10, 30, 20, 36, 57, 111, DateTimeKind.Utc).AddTicks(6631),
                            ProductId = 1,
                            PurchaseId = 1,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Demographic")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GlobalProductCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryColorCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecondaryColorCode")
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<string>("StyleNumber")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            Category = "Skateboarding",
                            DateCreated = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(4355),
                            DateModified = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(4847),
                            Demographic = "Men",
                            GlobalProductCode = "po-JZGOCQO",
                            ReleaseDate = new DateTime(2021, 10, 30, 15, 36, 57, 108, DateTimeKind.Local).AddTicks(3271),
                            Sku = "SHL-100-Blue",
                            StyleNumber = "scLFDVY",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            Category = "Soccer",
                            DateCreated = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5435),
                            DateModified = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5436),
                            Demographic = "Women",
                            GlobalProductCode = "po-DWEMRNT",
                            ReleaseDate = new DateTime(2021, 10, 30, 15, 36, 57, 110, DateTimeKind.Local).AddTicks(5277),
                            Sku = "SHL-100-Red",
                            StyleNumber = "scFYYPL",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            Category = "Football",
                            DateCreated = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5447),
                            DateModified = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5448),
                            Demographic = "Women",
                            GlobalProductCode = "po-DGGQMOV",
                            ReleaseDate = new DateTime(2021, 10, 30, 15, 36, 57, 110, DateTimeKind.Local).AddTicks(5443),
                            Sku = "HOV-AB-KJ",
                            StyleNumber = "scKILFU",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            Category = "Football",
                            DateCreated = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5455),
                            DateModified = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5456),
                            Demographic = "Women",
                            GlobalProductCode = "po-BXECFTK",
                            ReleaseDate = new DateTime(2021, 10, 30, 15, 36, 57, 110, DateTimeKind.Local).AddTicks(5453),
                            Sku = "TLX-DRESS-SM",
                            StyleNumber = "scIBFTG",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            Category = "Football",
                            DateCreated = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5462),
                            DateModified = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5463),
                            Demographic = "Men",
                            GlobalProductCode = "po-BIZRDQH",
                            ReleaseDate = new DateTime(2021, 10, 30, 15, 36, 57, 110, DateTimeKind.Local).AddTicks(5460),
                            Sku = "ATK-34-RD",
                            StyleNumber = "scZWELP",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            Category = "Baseball",
                            DateCreated = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5472),
                            DateModified = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5473),
                            Demographic = "Women",
                            GlobalProductCode = "po-NTGWAVE",
                            ReleaseDate = new DateTime(2021, 10, 30, 15, 36, 57, 110, DateTimeKind.Local).AddTicks(5470),
                            Sku = "TRE-33-LRG",
                            StyleNumber = "scBTMGT",
                            Type = "Pant"
                        },
                        new
                        {
                            Id = 7,
                            Active = false,
                            Category = "Football",
                            DateCreated = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5479),
                            DateModified = new DateTime(2021, 10, 30, 20, 36, 57, 110, DateTimeKind.Utc).AddTicks(5480),
                            Demographic = "Women",
                            GlobalProductCode = "po-EBXFARJ",
                            ReleaseDate = new DateTime(2021, 10, 30, 15, 36, 57, 110, DateTimeKind.Local).AddTicks(5478),
                            Sku = "TRE-30-SM",
                            StyleNumber = "scALORX",
                            Type = "Pant"
                        });
                });

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BillingCity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingPhone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("BillingState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("BillingStreet")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingStreet2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillingZip")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("CVV")
                        .HasColumnType("integer");

                    b.Property<string>("CardHolder")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeliveryCity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeliveryFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeliveryLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeliveryState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("DeliveryStreet")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeliveryStreet2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DeliveryZip")
                        .HasMaxLength(10)
                        .HasColumnType("integer");

                    b.Property<string>("Expiration")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingCity = "Atlanta",
                            BillingEmail = "customer@home.com",
                            BillingPhone = "(714) 345-8765",
                            BillingState = "GA",
                            BillingStreet = "123 Main",
                            BillingStreet2 = "Apt A",
                            BillingZip = "31675",
                            CVV = 456,
                            CardHolder = "Max Perkins",
                            CardNumber = "1435678998761234",
                            DateCreated = new DateTime(2021, 10, 30, 20, 36, 57, 112, DateTimeKind.Utc).AddTicks(2094),
                            DateModified = new DateTime(2021, 10, 30, 20, 36, 57, 112, DateTimeKind.Utc).AddTicks(2103),
                            DeliveryCity = "Birmingham",
                            DeliveryFirstName = "Max",
                            DeliveryLastName = "Space",
                            DeliveryState = "AL",
                            DeliveryStreet = "123 Hickley",
                            DeliveryZip = 43690,
                            Expiration = "11/21",
                            OrderDate = new DateTime(2021, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.LineItem", b =>
                {
                    b.HasOne("Catalyte.Aquitas.Data.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalyte.Aquitas.Data.Model.Purchase", "Purchase")
                        .WithMany("LineItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Catalyte.Aquitas.Data.Model.Purchase", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
